### ISSUE TITLE
Unicode issues when running updateAmaraMapping

### ISSUE THREAD

**Issue by ulikoehler** [alani1/KALanguageReport#10]
When running `python manage.py updateAmaraMapping` I get multiple of these tracebacks:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/tmp/KALanguageReport/LanguageStatistic/management/commands/updateAmaraMapping.py", line 26, in run
    self.lookupAmaraID(ytid)
  File "/tmp/KALanguageReport/LanguageStatistic/management/commands/updateAmaraMapping.py", line 35, in lookupAmaraID
    doc = utils.get_response_json(self.conn, query)
  File "/tmp/KALanguageReport/LanguageStatistic/utils.py", line 84, in get_response_json
    doc = get_response(conn, path, decode)
  File "/tmp/KALanguageReport/LanguageStatistic/utils.py", line 75, in get_response
    response = response.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 177: ordinal not in range(128)
```

I believe this can be fixed in the source code in some way, but in my experience this class of bugs can be easily fixed by using `python3`. Right now I believe it is acceptable to ignore the ~10 import errors.

**Comment by alani1** [comment]
Hi Uli,

I have been fighting alot with those unicode issues. I use python 2.6
because 2.7 is not available on my host. Normally it can be fixed by using
"from **future** import unicode_literals".

However updateAmaraMapping should be deprecated.  KA is moving away from
Amara, I have recently added a new Management Command called, updateVideos
(maybe not be the best naming), updateVideos gets the status of subtitles
from the KA translationportal (https://www.khanacademy.org/translations/de).

**Comment by ulikoehler** [comment]
Agreed. I think right now it's not worth worrying about the few records that are likely not imported.

**Comment by ulikoehler** [comment]
Just as a note: I tend to use distributions like Anaconda for hosts where more recent version of Python are not available. If you can afford the hard drive space, it might be worth a try in the future.
